In [28]:
import os
import numpy as np
from two_finger_image_dataset import TwoFingerImageDataset

zarr_path = os.path.expanduser('/data/scene-rep/u/iyu/scene-jacobian-discovery/diff-policy/diffusion_policy/data/two_finger/shadow_finger_box_qpos.zarr')
dataset = TwoFingerImageDataset(zarr_path, horizon=149)

In [32]:
idx = 0
print(len(dataset))
batch = dataset[idx]
print(batch.keys())
import mediapy as media
import torch

img = batch['obs']['image']
# reshape image to be (B, H, W, C)
print(img.shape)
img = img.permute(0, 2, 3, 1).numpy()
media.show_video(img, fps=12)

100
dict_keys(['obs', 'action'])
torch.Size([149, 3, 256, 256])


In [ ]:
from pathlib import Path
import pickle
import io
import gzip

class CPU_Unpickler(pickle.Unpickler):
    def find_class(self, module, name):
        if module == "torch.storage" and name == "_load_from_bytes":
            return lambda b: torch.load(io.BytesIO(b), map_location="cpu")
        # elif module == "jax.interpreters.xla" and name == "DeviceArray":
        #     return lambda b: jax.device_put(io.BytesIO(b), jax.devices("cpu")[0])
        else:
            return super().find_class(module, name)
     
        
def load_gzip_file(file_name):
    with gzip.open(file_name, "rb") as f:
        traj = CPU_Unpickler(f).load()
    return traj

In [3]:
states_path = Path("/data/scene-rep/u/sizheli/03-02-2025/00000/traj_data.pkl")
traj = load_gzip_file(states_path)

In [6]:
print(traj["states"])
print(traj["actions"])

[[ 2.2142856e-01 -2.6603823e-03 -2.8193960e-04 ... -0.0000000e+00
  -0.0000000e+00 -2.0750315e-01]
 [ 5.0511867e-01 -1.2599059e-03  4.4396973e-05 ... -0.0000000e+00
  -0.0000000e+00 -2.0750315e-01]
 [ 7.0478332e-01  2.0712321e-05 -2.4422831e-04 ... -0.0000000e+00
  -0.0000000e+00 -2.0750315e-01]
 ...
 [-5.5561084e-02  2.7478545e-03  7.2455800e-01 ... -0.0000000e+00
  -0.0000000e+00 -2.0750315e-01]
 [-5.5559322e-02  2.6423291e-03  7.2448087e-01 ... -0.0000000e+00
  -0.0000000e+00 -2.0750315e-01]
 [-5.5557564e-02  2.5408764e-03  7.2440678e-01 ... -0.0000000e+00
  -0.0000000e+00 -2.0750315e-01]]
[[ 1.0000000e+00 -8.8265955e-01  8.9529224e-02 -1.0000000e+00]
 [ 1.0000000e+00 -8.8265955e-01  8.9529224e-02 -1.0000000e+00]
 [ 1.0000000e+00 -8.8662654e-04  1.0000000e+00  3.9748335e-01]
 [ 1.0000000e+00 -8.8662654e-04  1.0000000e+00  3.9748335e-01]
 [ 4.4856095e-01  1.0000000e+00  7.0604151e-01 -1.0000000e+00]
 [ 4.4856095e-01  1.0000000e+00  7.0604151e-01 -1.0000000e+00]
 [-2.5170112e-01  9.86